Feat/dev 159 detect secrets
NCI-GDC/indexclient pull request #12
Opened 2020-05-01 01:22 UTC by asurinsaka

DEV-159 add pre-commit and detect-secrets

We would like to use pre-commit to perform various checks for us. 
Detecting secrets before committing is one use-case.

2020-05-15 21:32 UTC, ProfOak approved these changes

2020-07-18 19:06 UTC, philtom-ctds requested changes
Need to fix and update master before merging this pr.  I've opened prs to address master.  Blocking this pr for now

2020-07-20 20:26 UTC, asurinsaka commented
> Need to fix and update master before merging this pr. I've opened prs to address master. Blocking this pr for now

I do not need to do anything for this one, do I?

2020-07-21 22:26 UTC, philtom-ctds approved these changes

2020-07-21 22:26 UTC, merged